type t =
  | ErrorInitialize
  | ErrorFailure
  | ErrorSequence
  | ErrorDisabled
  | ErrorExclusive
  | ErrorAuthType
  | ErrorAuthMissing
  | ErrorPolicy
  | ErrorPCR
  | ErrorPCRChanged
  | ErrorUpgrade
  | ErrorTooManyContexts
  | ErrorAuthUnavailable
  | ErrorReboot
  | ErrorUnbalanced
  | ErrorCommandSize
  | ErrorCommandCode
  | ErrorAuthSize
  | ErrorAuthContext
  | ErrorNVRange
  | ErrorNVSize
  | ErrorNVLocked
  | ErrorNVAuthorization
  | ErrorNVUninitialized
  | ErrorNVSpace
  | ErrorNVDefined
  | ErrorBadContext
  | ErrorCpHash
  | ErrorParent
  | ErrorNeedsTest
  | ErrorNoResult
  | ErrorSensitive
  | ErrorAsymmetric
  | ErrorAttributes
  | ErrorHash
  | ErrorValue
  | ErrorHierarchy
  | ErrorKeySize
  | ErrorMGF
  | ErrorMode
  | ErrorType
  | ErrorHandle
  | ErrorKDF
  | ErrorRange
  | ErrorAuthFail
  | ErrorNonce
  | ErrorPP
  | ErrorScheme
  | ErrorSize
  | ErrorSymmetric
  | ErrorTag
  | ErrorSelector
  | ErrorInsufficient
  | ErrorSignature
  | ErrorKey
  | ErrorPolicyFail
  | ErrorIntegrity
  | ErrorTicket
  | ErrorReservedBits
  | ErrorBadAuth
  | ErrorExpired
  | ErrorPolicyCC
  | ErrorBinding
  | ErrorCurve
  | ErrorECCPoint

val to_int : t -> int
val of_int : int -> t option
val to_hex : t -> string
